name:                CA-DSL
version:             0.1.0.0
github:              "BrunoSpoletini/CellularAutomataEDSL"
license:             BSD-3-Clause
author:              "Bruno Spoletini"
maintainer:          "bruno_spoletini@hotmail.com"
copyright:           "2024 Bruno Spoletini"

extra-source-files:
- README.md
- src/parse.y

# Metadata used when publishing your package
# synopsis:            Cellular automata EDSL
# category:            Web

description:         Please see the README on GitHub at <https://github.com/BrunoSpoletini/CellularAutomataEDSL#readme>

dependencies:
- base # >= 4.7 && < 5
- threepenny-gui
- vector
- strict
- array
- directory

default-extensions:
- MultiWayIf
- FlexibleContexts
- TypeSynonymInstances
- FlexibleInstances

ghc-options:
- -Wall
- -Wno-unrecognised-pragmas
- -fno-warn-unused-do-bind
- -fno-warn-unused-matches
- -fno-warn-name-shadowing
- -fno-warn-incomplete-uni-patterns
- -fno-warn-incomplete-patterns
- -fno-warn-type-defaults
- -fno-warn-noncanonical-monad-instances

library:
  source-dirs: src

executables:
  CA-DSL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CA-DSL
    build-tools:
    - happy