name:                CA-DSL
version:             0.1.0.0
github:              "brunospoletini/CA-DSL"
license:             BSD-3-Clause
author:              "Bruno Spoletini"
maintainer:          "bruno_spoletini@hotmail.com"
copyright:           "2024 Bruno Spoletini"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/CA-DSL#readme>

dependencies:
- base # >= 4.7 && < 5
- threepenny-gui
- colour
- containers
- vector
- strict # to use strict tuples (:!:)
- array
- pretty
- haskeline
- exceptions
- mtl
- parallel
- transformers
- aeson
- directory

default-extensions:
- MultiWayIf
- FlexibleContexts
- TypeSynonymInstances
- FlexibleInstances

ghc-options:
- -Wall
- -Wno-unrecognised-pragmas
- -Wnoncanonical-monad-instances
- -fno-warn-unused-do-bind
- -fno-warn-unused-matches
- -fno-warn-name-shadowing
- -fno-warn-incomplete-uni-patterns
- -fno-warn-incomplete-patterns
- -fno-warn-type-defaults
# - -Wunused-matches
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src

executables:
  CA-DSL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CA-DSL